config/routes.rb
Jam::Application.routes.draw do
  
  devise_for :users
  resources :users
  resources :messages
  resources :conversations
  resources :microposts, only: [:create, :destroy]
  resources :targetships

  match 'detruire_compte', to: 'users#destroy', via: 'delete'
  match 'data', to: 'users#data', via: 'get'
  match 'search', to: 'users#search', via: 'get'

  match 'reply', to: 'conversations#reply', via: 'post'

  match 'accepter_contact', to: 'targetships#accept', via: 'get'
  match 'refuser_contact', to: 'targetships#decline', via: 'get'

  match 'home', to: 'pages_statiques#home', via: 'get'
  match 'landing', to: 'pages_statiques#landing', via: 'get'
  match 'apropos', to: 'pages_statiques#apropos', via: 'get'
  match 'mentionslegales', to: 'pages_statiques#mentionslegales', via: 'get'
  match 'contact', to: 'pages_statiques#contact', via: 'get'
  match 'blog', to: 'pages_statiques#blog', via: 'get'

  root 'pages_statiques#home'
  

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	def new
		@user = User.find(params[:user_id])
	end

	def create
		destinataire = User.find(params[:user_id])
		@subject = params[:subject]
		@message = params[:message]	
		current_user.send_message(destinataire, "#{@message}", "#{@subject}")
		notification = Notification.last
		redirect_to conversation_path(notification.conversation_id)
	end

	def show
		@message = Receipt.find(params[:id])	
	end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_receiver_choice.html.erb
<ul>
	<%- @users.each do |u|%>
		<li>
			<%= radio_button_tag(:id, u.id) %>
			<%= image_tag u.avatar.url(:thumb) %>
			<%= u.name %>
		</li>
	<% end %>
</ul>

app/views/messages/new.html.erb
<div class="row">

  <div class="small-6 small-centered column">

    <p>Message destiné à <%=@user.name%></p>

  	<%= form_tag(messages_path) do  %>
      <%= hidden_field_tag :user_id, @user.id %> 
      <%= text_field_tag :subject, nil, :placeholder => "Sujet" %>
      <%= text_area_tag :message, nil, :placeholder => "Message" %>
      <%= submit_tag "Envoyer", :class => "submit" %>
    <% end %>

  </div>

</div>

app/views/messages/show.html.erb
<!-- inutilisé  -->

<div class="row">

  <div class="small-6 small-centered column">

	 <%= @notifications.subject %>
	 <%= @notifications.body %> 

  </div>

 </div>