config/routes.rb
Jam::Application.routes.draw do
  
  devise_for :users
  resources :users
  resources :messages
  resources :conversations
  resources :microposts, only: [:create, :destroy]
  resources :targetships

  match 'detruire_compte', to: 'users#destroy', via: 'delete'
  match 'data', to: 'users#data', via: 'get'
  match 'search', to: 'users#search', via: 'get'

  match 'reply', to: 'conversations#reply', via: 'post'

  match 'accepter_contact', to: 'targetships#accept', via: 'get'
  match 'refuser_contact', to: 'targetships#decline', via: 'get'

  match 'home', to: 'pages_statiques#home', via: 'get'
  match 'landing', to: 'pages_statiques#landing', via: 'get'
  match 'apropos', to: 'pages_statiques#apropos', via: 'get'
  match 'mentionslegales', to: 'pages_statiques#mentionslegales', via: 'get'
  match 'contact', to: 'pages_statiques#contact', via: 'get'
  match 'blog', to: 'pages_statiques#blog', via: 'get'

  root 'pages_statiques#home'
  

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

	def new
	end

	def create
		@conversation = Conversation.create!
		redirect_to action: 'index'
	end

	def index
		if current_user.mailbox.conversations.any?
		@conversations = current_user.mailbox.conversations
		end
	end	

	def show
		@conversation = Conversation.find(params[:id])
		@target = @conversation.recipients.find { |u| u!=current_user}
	end

	def reply
		conversation=Conversation.find(params[:id])
		@message = params[:message]
		current_user.reply_to_conversation(conversation, "#{@message}")
		redirect_to conversation_path(params[:id])
	end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/index.html.erb
<div class="row">

  <div class="small-8 small-centered column">

  	<h2>Demandes de contact en attente</h2>

		<%if current_user.requested_targets.any? %>

			<% current_user.requested_targets.each do |t|%>
				<div class="requete_contact">
					<%= image_tag t.avatar.url(:thumb) %>
					<%= t.name %>
					<%= t.age %>
					<%= t.ville %>
					<%= link_to "Profil", user_path(id: t.id), class: "button"%>
					<%= link_to "Accepter", accepter_contact_path(target_id: t.id), class: "button"%>
					<%= link_to "Refuser", refuser_contact_path(target_id: t.id), class: "button"%>
				</div>		
			<%end%>

		<%else%><p>Pas de demande de contact</p>
		<%end%>

  	<h2>Conversations en cours</h2>

  	<%if current_user.mailbox.conversations.any?%>
  	
		<%@conversations.each do |conv|%>
		    <div class="ligne_conversation">
		    <ul>
		    	<%= link_to conversation_path(conv.id) do%>
			        <li>
			        	<%correspondant=conv.participants.find do |u|%>
  								<%u.id != current_user.id%>
						<% end %>

			        	<%=image_tag correspondant.avatar.url(:thumb) %>
			        	<%=correspondant.name%>			        
			        	<%=conv.messages.last.body%>
			        </li>
			    <% end %>
		    </ul></div>
		<% end %>
		
	<%else%>
		<p>Pas de message pour l'instant</p>
	<%end%>	
	<br/>
  	
  </div>

</div>

app/views/conversations/new.html.erb
<!-- inutilisé -->

<div class="row">

	<div class="small-6 small-centered column">

		<h2>Nouvelle conversation</h2>

		<h3>Choisir un destinataire</h3>

		<%= render 'users/receiver_choice' %>

	</div>

</div>

app/views/conversations/show.html.erb
<div class="row">

  <div class="small-8 small-offset-1 column conversation_header">

  	    <div class="small-5 small-offset-1 column">
  	    	<%= image_tag @target.avatar.url(:thumb) %>
  	    	<%= @target.name %>
  	    </div>

  	    <div class="small-4 small-offset-1 column">
  	    	<%= image_tag current_user.avatar.url(:thumb) %>
  	    	<%= current_user.name%> 
  	    </div>

  	    <div class="small-1 column"></div>
  </div>

  <div class="small-3 column">
  	Jeux
  </div>

</div>

<div class="row">

  <div class="small-8 small-offset-1 column">

  	<%@conversation.messages.each do |message|%>

  		<div class="row">

	  		<div class="small-5 column ligne_message">			  		
			  	<%if message.sender_id==@target.id%>
			  		<div class="bloc_message"><%= message.body %></div>				
				<%end%>						
			</div>

	  	    <div class="small-5 small-offset-1 column ligne_message">			  		
				<%if message.sender_id==current_user.id%>
					<div class="bloc_message"><%= message.body %></div>			
				<%end%>						
			</div>

  	    	<div class="small-1 column"></div>
  	    </div>
  	    
  	<%end%>	
  </div>

  <div class="small-3 column"></div>

</div>
 
<div class="row">

	<div class="small-8 small-offset-1 column">
		<div class="formulaire_reponse">
			<%= render 'reply_form' %>
		</div>
	</div>

	<div class="small-3 column"></div>
</div>
	