config/routes.rb
Jam::Application.routes.draw do
  
  devise_for :users
  resources :users
  resources :messages
  resources :conversations
  resources :microposts, only: [:create, :destroy]
  resources :targetships

  match 'detruire_compte', to: 'users#destroy', via: 'delete'
  match 'data', to: 'users#data', via: 'get'
  match 'search', to: 'users#search', via: 'get'

  match 'reply', to: 'conversations#reply', via: 'post'

  match 'accepter_contact', to: 'targetships#accept', via: 'get'
  match 'refuser_contact', to: 'targetships#decline', via: 'get'

  match 'home', to: 'pages_statiques#home', via: 'get'
  match 'landing', to: 'pages_statiques#landing', via: 'get'
  match 'apropos', to: 'pages_statiques#apropos', via: 'get'
  match 'mentionslegales', to: 'pages_statiques#mentionslegales', via: 'get'
  match 'contact', to: 'pages_statiques#contact', via: 'get'
  match 'blog', to: 'pages_statiques#blog', via: 'get'

  root 'pages_statiques#home'
  

end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :microposts, dependent: :destroy
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
		uniqueness: true
	validates :name, presence: true, length: { maximum: 25 }
	validates :age, presence: true
	# validates :sexe, presence: true, inclusion: { in: %w(masculin feminin autre)}
	validates :ville, presence: true

	# gestion de la prise de contact, mise en relation
	has_many :targetships
	has_many :targets, :through => :targetships, 
				:conditions => "status = 'accepted'"
	has_many :requested_targets, :through => :targetships, :source => :target,
				:conditions => "status = 'requested'"
	has_many :pending_targets, :through => :targetships, :source => :target,
				:conditions => "status = 'pending'"

	# flux de statuts sur la home page 

	def feed

		feed=[]
		User.find_each do |u|
			if u.microposts.any?
				feed << u.microposts.first
			end		
		end
		return feed.sort! { |a,b| b.created_at <=> a.created_at }

	end

	# devise
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
 	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    #paperclip
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/	

	#particularités de mailboxer 

	acts_as_messageable
	
	#Returning any kind of identification you want for the model
	# def name
	# end

	#Returning the email address of the model if an email should be sent for this object (Message or Notification).
	#If no mail has to be sent, return nil.
	def mailboxer_email(object)
	  #Check if an email should be sent for that object
	  #if true
	  return "define_email@on_your.model"
	  #if false
	  #return nil
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :authenticate_user!

	def new
		@user = User.new
	end

	def index
		# @user = User.all
		@q = User.search(params[:q])
  		@user = @q.result(distinct: true)
	end
		
	def create
	 	@user = User.create(user_params)
	end

	def show
		@user = User.find(params[:id])
		@micropost = current_user.microposts.build
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.update_attributes(user_params)
		flash[:success] = "Profile updated"
		redirect_to @user
	end
		
	def destroy
		@user = current_user
		@user.destroy
		redirect_to new_user_session_path
	end

	def data
		@user = current_user
	end	

	private

	# Use strong_parameters for attribute whitelisting
	# Be sure to update your create() and update() controller methods.

	def user_params
	  params.require(:user).permit(:avatar, :age, :sexe, :orientation, :ville, :cheveux, :yeux, 
	  	:taille, :bodytype, :profession, :religion, :astral, :annonce)
	end	

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/data.html.erb
<div class="row">
	<div class="small-6 columns">
		<h1>DATAS</h1>
		<p>Liste des contacts de <%=current_user.name%></p>
		<ul>
			<% for user in @user.targets %>
			    <li><%= link_to(user) do %>
			  		<%= image_tag user.avatar.url(:thumb) %>
			   		<%= user.name %><%end%>
			   	</li>
			<% end %> 
		</ul> 
	</div>
</div>

app/views/users/edit.html.erb
<div class="row">

  <div class="small-6 small-centered column">

    <div class="form">

      <%= form_for current_user do |f| %>

        <div class="submit">
          <%= f.submit "Enregistrer les modifications" %>
        </div>

        <div class="avatar">
          <%= f.label :avatar %>
          <%= f.file_field :avatar %>
        </div>

        <%= f.label :annonce %>
        <%= f.text_area :annonce %>

        <%= f.label :age %>
        <%= f.number_field :age %>

        <%= f.label :sexe %>
        <%= f.select(:sexe, options_for_select([[nil],['Masculin'], ['Féminin'], ['Autre']])) %>

        <%= f.label :orientation %>
        <%= f.select(:orientation, options_for_select([[nil],['Hétérosexuel'], ['Homosexuel'], ['Bisexuel']])) %>

        <%= f.label :ville %>
        <%= f.text_field :ville %>

        <%= f.label :cheveux %>
        <%= f.select(:cheveux, options_for_select([[nil],['Bruns'], ['Châtains'], ['Roux'], ['Blonds'], ['Blancs'], ['Custom'], ['Rares']])) %>

        <%= f.label :yeux %>
        <%= f.select(:yeux, options_for_select([[nil],['Noirs'], ['Marrons'], ['Verts'], ['Bleus']])) %>

        <%= f.label :taille %>
        <%= f.number_field :taille, placeholder: "en centimètres"%>

        <%= f.label "Type physique" %>
        <%= f.select(:bodytype, options_for_select([[nil],['Mince'], ['Sportif'], ['Classique'], ['Rond'], ['Pulpeux']])) %>

        <%= f.label :profession %>
        <%= f.text_field :profession %>

        <%= f.label :religion %>
        <%= f.text_field :religion %>

        <%= f.label "Signe astral" %>
        <%= f.select(:astral, options_for_select([[nil],['Capricorne'], ['Verseau'], ['Poissons'], ['Bélier'], ['Taureau'], ['Gémeaux'], ['Cancer'], ['Lion'], ['Vierge'], ['Balance'], ['Scorpion'], ['Sagitaire']])) %>

        <div class="submit">
          <%= f.submit "Enregistrer les modifications" %>
        </div>

      <% end %>
    </div>

  </div>

</div>

app/views/users/inbox.html.erb
<div class="row">

  <div class="small-6 small-centered column samplecontainer">

  	<h1>Boite mail</h1>
  	<%= current_user.mailbox%>
  </div>

</div>

app/views/users/index.html.erb
<h2>Zone de recherche</h2>
<div class="row">

	<div class="small-4 column colonne_criteres panel">

		<!-- formulaire de recherche  -->
		<%= search_form_for @q do |f| %>
		
		<div class="bouton_recherche">
			<%= f.submit "Lancer la recherche", class: "button" %>
		</div>

		<div class="row">
			
				<div class="small-5 column">
					<%= f.label(:sexe_cont, "Sexe", class: "inline")%>
				</div>

				<div class="small-7 column">
			        <%= f.select(:sexe_cont, options_for_select([[nil],['Masculin'], ['Féminin'], ['Autre']], @q.sexe_cont)) %>
			    </div>
			 
		</div>

		<div class="row">
			<div class="small-5 column">
				<%= f.label(:orientation_cont, "Orientation", class: "inline")%>
			</div>

			<div class="small-7 column">
				<%= f.select(:orientation_cont, options_for_select([[nil],['Hétérosexuel'], ['Homosexuel'], ['Bisexuel']], @q.orientation_cont)) %>
		    </div> 
		</div>

		<div class="row">
			<div class="small-5 column">
				<%= f.label(:age_gt, "Age minimum", class: "inline")%>
			</div>

			<div class="small-7 column">
				<%= f.number_field(:age_gt) %>
		    </div> 
		</div>

		<div class="row">
			<div class="small-5 column">
				<%= f.label(:age_lt, "Age maximum", class: "inline")%>
			</div>

			<div class="small-7 column">
				<%= f.number_field(:age_lt) %>
		    </div> 
		</div>
	    
	    <div class="row">
			<div class="small-5 column">
				<label for="localisation" class="center inline">(Localisation)</label>
			</div>

			<div class="small-7 column">
				<select for="localisation">
					<option selected></option>
			        <option value=5>- de 5 km</option>
			        <option value=10>- de 10 km</option>
			        <option value=50>- de 50 km</option>
		        </select>	
		    </div> 
		</div>

		<div class="row">
			<div class="small-5 column">
				<label for="avec_photo" class="center inline">(Avec une photo)</label>
			</div>

			<div class="small-7 column">
				<select for="localisation">
					<option selected></option>
			        <option value="oui">Oui</option>
			        <option value="non">Non</option>
		        </select>	
		    </div> 
		</div>

		<div class="row">
			<div class="small-5 column">
				<%= f.label(:cheveux_cont, "Cheveux", class: "inline")%>
			</div>

			<div class="small-7 column">
				<%= f.select(:cheveux_cont, options_for_select([[nil],['Bruns'], ['Châtains'], ['Roux'], ['Blonds'], ['Blancs'], ['Custom'], ['Rares']], @q.cheveux_cont)) %>
		    </div> 
		</div>

		<div class="row">
			<div class="small-5 column">
				<%= f.label(:yeux_cont, "Yeux", class: "inline")%>
			</div>

			<div class="small-7 column">
				<%= f.select(:yeux_cont, options_for_select([[nil],['Noirs'], ['Marrons'], ['Verts'], ['Bleus']], @q.yeux_cont)) %>
		    </div> 
		</div>

		<div class="row">
			<div class="small-5 column">
				<%= f.label(:taille_gt, "Taille minimum", class: "inline")%>
			</div>

			<div class="small-7 column">
				<%= f.number_field(:taille_gt, placeholder: "En centimètres") %>
		    </div> 
		</div>

		<div class="row">
			<div class="small-5 column">
				<%= f.label(:taille_lt, "Taille maximum", class: "inline")%>
			</div>

			<div class="small-7 column">
				<%= f.number_field(:taille_lt, placeholder: "En centimètres") %>
		    </div> 
		</div>

		<div class="row">
			<div class="small-5 column">
				<%= f.label(:bodytype_cont, "Type physique", class: "inline")%>
			</div>

			<div class="small-7 column">
				<%= f.select(:bodytype_cont, options_for_select([[nil],['Mince'], ['Sportif'], ['Classique'], ['Rond'], ['Pulpeux']], @q.bodytype_cont)) %>
		    </div> 
		</div>

		<div class="row">
			<div class="small-5 column">
				<label for="profession" class="center inline">(Profession)</label>
			</div>

			<div class="small-7 column">
				<input type="text" for="profession"/>
		    </div> 
		</div>

		<div class="row">
			<div class="small-5 column">
				<label for="religion" class="center inline">(Religion)</label>
			</div>

			<div class="small-7 column">
				<input type="text" for="religion"/>
		    </div> 
		</div>

		<div class="row">
			<div class="small-5 column">
				<%= f.label(:astral_cont, "Signe Astral", class: "inline")%>
			</div>

			<div class="small-7 column">
				<%= f.select(:astral_cont, options_for_select([[nil],['Capricorne'], ['Verseau'], ['Poissons'], ['Bélier'], ['Taureau'], ['Gémeaux'], ['Cancer'], ['Lion'], ['Vierge'], ['Balance'], ['Scorpion'], ['Sagitaire']], @q.astral_cont)) %>
		    </div> 
		</div>

		<div class="row">
			<div class="small-5 column">
				<label for="regime_alimentaire" class="center inline">(Régime)</label>
			</div>

			<div class="small-7 column">
				<select for="regime_alimentaire">
					<option selected></option>
			        <option value="tout">Mange de tout</option>
			        <option value="vegetarien">Végétarien</option>
			        <option value="vegetalien">Végétalien</option>
			        <option value="interdits_religieux">Interdits religieux</option>
		        </select>	
		    </div> 
		</div>

		<div class="row">
			<div class="small-5 column">
				<label for="badges" class="center inline">(Badges)</label>
			</div>

			<div class="small-7 column">
				<select for="badges">
					<option selected></option>
			        <option value="1">1</option>
			        <option value="2">2</option>
		        </select>	
		    </div> 
		</div>

		<div class="row">
			<div class="small-5 column">
				<label for="resultat_test_1" class="center inline">(Résultat test 1)</label>
			</div>

			<div class="small-7 column">
				<select for="resultat_test_1">
					<option selected></option>
			        <option value="1">1</option>
			        <option value="2">2</option>
		        </select>	
		    </div> 
		</div>

		<div class="row">
			<div class="small-5 column">
				<label for="resultat_test_2" class="center inline">(Résultat test 2)</label>
			</div>

			<div class="small-7 column">
				<select for="resultat_test_1">
					<option selected></option>
			        <option value="1">1</option>
			        <option value="2">2</option>
		        </select>	
		    </div> 
		</div>

		<div class="row">
			<div class="small-5 column">
				<label for="pseudo" class="center inline">(Pseudo)</label>
			</div>

			<div class="small-7 column">
				<input type="text" for="pseudo"/>
		    </div> 
		</div>

		<div class="row">
			<div class="small-5 column">
				<label for="mot_cle" class="center inline">(Mot clé)</label>
			</div>

			<div class="small-7 column">
				<input type="text" for="mot_cle"/>
		    </div> 
		</div>

		<div class="bouton_recherche">
			<%= link_to "Lancer la recherche", "#", class: "button" %>
		</div>

	<%end%>   

	</div>

	<!-- affichage des résultats  -->
	
	<div class="small-4 column">
		<% @user.each do |u| %>
			<div class="item_list_users">
				<%if u.id%2==1%>
					<%= link_to user_path(u.id) do %>
						<%= image_tag u.avatar.url(:thumb) %> <%=u.name%>
							<%=u.age%> ans <%=u.ville%>
					<%end%><br><hr>
				<%end%>		
			</div>
		<%end%>	
	</div>
	

	<div class="small-4 column">
		<% @user.each do |u| %>
			<div class="item_list_users">
				<%if u.id%2==0%>
					<%= link_to user_path(u.id) do %>
						<%= image_tag u.avatar.url(:thumb) %> <%=u.name%>
							<%=u.age%> ans <%=u.ville%>
					<%end%><br><hr>
				<%end%>		
			</div>
		<%end%>
	</div>
	
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="small-11 column">

	<div class="row">

		<div class="small-4 columns bloc_pseudo">
			<h1><%= @user.name %></h1>
		</div>

		<div class="small-4 columns panel bloc_statut">

			<% if @user==current_user %>
				<% if @user.microposts.any? %>
					<%= render 'shared/micropost_form' %>
		            <%= @user.microposts.first.content %>
		            <p>publié il y a <%= time_ago_in_words(@user.microposts.first.created_at)%></p>	            
		        <% else %>
					<%= render 'shared/micropost_form' %>
				<%end%>
			<% else %>
				<% if @user.microposts.any? %>
					<%= @user.microposts.first.content %>
				<%end%>
			<%end%>
		</div>

		<div class="small-3 small-offset-1 columns update">
			
			<% if @user==current_user %>
				<%= link_to "Modifier le profil", edit_user_path(:user_id => current_user.id), class: "button" %>
			<%else%>
				
				<%if current_user.targets.include?(@user) %>
					<%= link_to "Nouveau message", new_message_path(:user_id => @user.id), class: "button" %>
				<%else%>
					<%unless current_user.requested_targets.include?(@user)||current_user.pending_targets.include?(@user)%>
						<%=link_to"Entrer en contact", targetships_path(:target_id => @user.id), :method => :post, class: "button"%>
					<%end%>
				<%end%>	
				
			<%end%>

		</div>

	</div>

	<div class="row">

		<div class="small-4 columns">
			<%= image_tag @user.avatar.url(:medium) %>	
		</div>

		<div class="small-4 columns">
			<p>
			<%= if @user.annonce.present? then @user.annonce else 
				if @user == current_user then
				"Présentez-vous en quelques mots, les autres utilisateurs ont envie de mieux vous connaître !"
				else "#{@user.name} n'a pas encore rempli son profil"
				end	
			end%>
			</p>
		</div>

		<div class="small-4 columns bloc_info">

			<div class="row">

				<div class="small-6 columns">

					<ul>

						<li>Age</li>
						<li>Sexe</li>
						<li>Orientation</li>
						<li>Ville</li>
						<li>Cheveux</li>
						<li>Yeux</li>
						<li>Taille</li>
						<li>Type physique</li>
						<li>Profession</li>
						<li>Religion</li>
						<li>Signe astral</li>

					</ul>

				</div>

				<div class="small-6 columns">
					<ul> 
						<li><%= if @user.age.present? then "#{@user.age} ans" else "---" end%></li>
						<li><%= if @user.sexe.present? then @user.sexe else "---" end%></li>
						<li><%= if @user.orientation.present? then @user.orientation else "---" end%></li>
						<li><%= if @user.ville.present? then @user.ville else "---" end%></li>
						<li><%= if @user.cheveux.present? then @user.cheveux else "---" end%></li>
						<li><%= if @user.yeux.present? then @user.yeux else "---" end%></li>
						<li><%= if @user.taille.present? then "#{@user.taille} cm" else "---" end%></li>
						<li><%= if @user.bodytype.present? then @user.bodytype else "---" end%></li>
						<li><%= if @user.profession.present? then @user.profession else "---" end%></li>
						<li><%= if @user.religion.present? then @user.religion else "---" end%></li>
						<li><%= if @user.astral.present? then @user.astral else "---" end%></li>
					</ul>
				</div>

			</div>
		</div>
	</div>

	<div class="row">

		<div class="small-8 columns">

			<div class="badges">
				<h3>Badges</h3>
				<div class="row">
					<div class="small-2 small-offset-1 columns">
						<i class="fi-crown"></i>
					</div>
					<div class="small-2 columns">
						<i class="fi-shield"></i>
					</div>
					<div class="small-2 columns">
						<i class="fi-megaphone"></i>
					</div>
					<div class="small-2 columns">
						<i class="fi-trophy"></i>
					</div>
					<div class="small-2 columns">
						<i class="fi-target-two"></i>
					</div>
					<div class="small-1 columns"></div>
				</div>

				<div class="row">
					<div class="small-2 small-offset-1 columns">
						<i class="fi-skull"></i>
					</div>
					<div class="small-2 columns">
						<i class="fi-sheriff-badge"></i>
					</div>
					<div class="small-2 columns">
						<i class="fi-paw"></i>
					</div>
					<div class="small-2 columns">
						<i class="fi-music"></i>
					</div>
					<div class="small-3 columns"></div>
				</div>
				
			</div>

			<div class="tests">			
				<h3>Tests</h3>
				<div class="row">
					<div class="small-2 small-offset-1 columns">
						<i class="fi-lock"></i>
						<p>Séduction</p>
					</div>
					<div class="small-2 columns">
						<i class="fi-lock"></i>
						<p>Sexo</p>
					</div>
					<div class="small-2 columns">
						<i class="fi-lock"></i>
						<p>Couple</p>
					</div>
					<div class="small-2 columns">
						<i class="fi-lock"></i>
						<p>Ethique</p>
					</div>
					<div class="small-2 columns">
						<i class="fi-lock"></i>
						<p>Lyfestyle</p>
					</div>
					<div class="small-1 columns"></div>
				</div>
			</div>

			<div class="notes">
				<h3>Notes</h3>
				<div class="row">
					<div class="small-3 columns">
						<p>Fidélité du profil</p>
					</div>
					<div class="small-2 columns">
						<i class="fi-star"></i>
						<i class="fi-star"></i>
						<i class="fi-star"></i>
						<i class="fi-star"></i>
						<i class="fi-star"></i>
					</div>
					<div class="small-3 small-offset-1 columns">
						<p>Humour</p>
					</div>
					<div class="small-2 columns">
						<i class="fi-star"></i>
						<i class="fi-star"></i>
						<i class="fi-star"></i>
						<i class="fi-star"></i>
						<i class="fi-star"></i>
					</div>
					<div class="small-1 columns"></div>
				</div>

				<div class="row">
					<div class="small-3 columns">
						<p>Conversation</p>
					</div>
					<div class="small-2 columns">
						<i class="fi-star"></i>
						<i class="fi-star"></i>
						<i class="fi-star"></i>
						<i class="fi-star"></i>
						<i class="fi-star"></i>
					</div>
					<div class="small-3 small-offset-1 columns">
						<p>Initiative</p>
					</div>
					<div class="small-2 columns">
						<i class="fi-star"></i>
						<i class="fi-star"></i>
						<i class="fi-star"></i>
						<i class="fi-star"></i>
						<i class="fi-star"></i>
					</div>
					<div class="small-1 columns"></div>
				</div>

				<div class="row">
					<div class="small-3 columns">
						<p>Partage</p>
					</div>
					<div class="small-2 columns">
						<i class="fi-star"></i>
						<i class="fi-star"></i>
						<i class="fi-star"></i>
						<i class="fi-star"></i>
						<i class="fi-star"></i>
					</div>
					<div class="small-3 small-offset-1 columns">
						<p>Surprise</p>
					</div>
					<div class="small-2 columns">
						<i class="fi-star"></i>
						<i class="fi-star"></i>
						<i class="fi-star"></i>
						<i class="fi-star"></i>
						<i class="fi-star"></i>
					</div>
					<div class="small-1 columns"></div>
				</div>

				<div class="row">
					<div class="small-3 columns">
						<p>Energie</p>
					</div>
					<div class="small-2 columns">
						<i class="fi-star"></i>
						<i class="fi-star"></i>
						<i class="fi-star"></i>
						<i class="fi-star"></i>
						<i class="fi-star"></i>
					</div>
					<div class="small-3 small-offset-1 columns">
						<p>Ecoute</p>
					</div>
					<div class="small-2 columns">
						<i class="fi-star"></i>
						<i class="fi-star"></i>
						<i class="fi-star"></i>
						<i class="fi-star"></i>
						<i class="fi-star"></i>
					</div>
					<div class="small-1 columns"></div>
				</div>


			</div>

		</div>

		<div class="small-4 columns">

			<div>
				<p>Musique</p>
				<p>Cinéma</p>
				<p>Séries TV</p>
				<p>Littérature</p>
			</div>

			<div class="contenu">
				<h3>Contenu</h3>
				<iframe width="300" height="225" src="//www.youtube.com/embed/rlfHcCLn4pk" frameborder="0" allowfullscreen></iframe>
			
				<iframe width="100%" height="300" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/113781204&amp;auto_play=false&amp;hide_related=false&amp;visual=true"></iframe>
			</div>

		</div>

	</div>
  </div>
  <div class="small-1 column"></div>
</div>