config/routes.rb
Jam::Application.routes.draw do
  
  devise_for :users
  resources :users
  resources :messages
  resources :conversations
  resources :microposts, only: [:create, :destroy]
  resources :targetships

  match 'detruire_compte', to: 'users#destroy', via: 'delete'
  match 'data', to: 'users#data', via: 'get'
  match 'search', to: 'users#search', via: 'get'

  match 'reply', to: 'conversations#reply', via: 'post'

  match 'accepter_contact', to: 'targetships#accept', via: 'get'
  match 'refuser_contact', to: 'targetships#decline', via: 'get'

  match 'home', to: 'pages_statiques#home', via: 'get'
  match 'landing', to: 'pages_statiques#landing', via: 'get'
  match 'apropos', to: 'pages_statiques#apropos', via: 'get'
  match 'mentionslegales', to: 'pages_statiques#mentionslegales', via: 'get'
  match 'contact', to: 'pages_statiques#contact', via: 'get'
  match 'blog', to: 'pages_statiques#blog', via: 'get'

  root 'pages_statiques#home'
  

end

app/views/layouts/_footer.html.erb
<footer>
	<div class="row">
		<div class="small-5 small-centered columns">
			<nav class="breadcrumbs">
				<a href="<%=blog_path%>">Blog</a>
				<a href="<%=apropos_path%>">A propos</a>
				<a href="<%=contact_path%>">Contact</a>
				<a href="<%=mentionslegales_path%>">Mentions légales</a>
			</nav>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header>
  	<nav class="top-bar" data-topbar>

  		<ul class="title-area">
    		<li class="name">
      			<h1><a href="<%=root_path%>">Joue Avec Moi</a></h1>
    		</li>
 		</ul>

		<section class="top-bar-section">
		
			<!-- Right Nav Section -->
			<ul class="right">

			    <li><a href="<%=home_path%>"><i class="fi-home iconenav active"></i></a></li>
			    <li><a href="/users/<%=current_user.id%>"><i class="fi-torso iconenav"></i></a></li>
			    <li><a href="/users"><i class="fi-magnifying-glass iconenav"></i></a></li>
			    <li><a href="/conversations"><i class="fi-mail iconenav"></i></a></li>
			    <li><a href="<%=data_path%>"><i class="fi-graph-bar iconenav"></i></a></li>
			    <li class="has-dropdown not-click">
			        <a href="#"><i class="fi-widget iconenav"></i></a>
			        <ul class="dropdown">
			          <li><%=link_to('Déconnexion', destroy_user_session_path, :method => :delete)%></li>
			          <li><%=link_to('Détruire compte', detruire_compte_path, :method => :delete, data: { confirm: "Vraiment?"})%></li>
			        </ul>
			    </li>
			</ul>

	    </section>
	</nav>
</header>

app/views/layouts/_isu.html.erb
<!-- interface site utilisteur \o/ -->
<div class="isu">
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
</div>

app/views/layouts/_level.html.erb
<div class="level_box">
	<div class="pseudo_isu"><%=current_user.name%></div>
	<div class="progress"> 
		<span class="meter" style="width: 30%"></span> 
	</div>
	<div class="level">Niveau 1</div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Joue avec moi" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= if user_signed_in? then render 'layouts/header' end%>
    
    <div class="row">
      <div class="small-2 column">
        <div class="row">
          <div class="small-10 small-centered column">
            <%= if user_signed_in? then render 'layouts/level' end%>
            <%= if user_signed_in? then render 'layouts/isu' end%>
          </div>
        </div>
      </div>


      <div class="small-10 column">
        <%= yield %>
      </div>
    </div>

    <div class="row">
      <%= if user_signed_in? then render 'layouts/footer' end%>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>